export { Introduction } from './Introduction/Introduction';
export { Header } from './Header/Header';
export { Socials } from './Socials/Socials';
export { About } from './About/About';
export { Link } from './Link/Link';
export { Nav } from './Nav/Nav';
export { Knowledge } from './Knowledge/Knowledge';
export { Projects } from './Proyectos/Projects';
export { Footer } from './Footer/Footer';
